---
- name: System configuration
  hosts: all

  roles:
    - dannixon.system.package_updates
    - dannixon.system.system
    - dannixon.system.inspection_tools
    - dannixon.system.interactive_users
    - dannixon.services.sshd
    - isis_archive
    - isis_cephfs

  tasks:
    - name: Ensure firewall is enabled
      become: true
      community.general.ufw:
        state: enabled
        policy: deny

    - name: Ensure SSH is allowed through firewall
      become: true
      community.general.ufw:
        rule: limit
        port: ssh
        proto: tcp
