---
- name: Deployment
  delegate_to: localhost
  run_once: true
  block:
    - name: Ensure Helm repository is available
      kubernetes.core.helm_repository:
        name: longhorn
        repo_url: https://charts.longhorn.io
        state: present

    - name: Ensure Longhorn is deployed
      kubernetes.core.helm:
        name: longhorn
        namespace: longhorn-system
        create_namespace: true
        chart_ref: longhorn/longhorn
        values:
          defaultSettings:
            backupTarget: "{{ longhorn_s3_backup_target if longhorn_s3_backup_enabled else None }}"
            backupTargetCredentialSecret: "{{ longhorn_s3_backup_secret_name }}"
        state: present

    - name: Ensure S3 configuration is present if required
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: "{{ longhorn_s3_backup_secret_name }}"
            namespace: longhorn-system
          data:
            AWS_ACCESS_KEY_ID: "{{ longhorn_s3_backup_key_id | b64encode }}"
            AWS_SECRET_ACCESS_KEY: "{{ longhorn_s3_backup_key_secret | b64encode }}"
            AWS_ENDPOINTS: "{{ longhorn_s3_backup_endpoint | b64encode }}"
        state: "{{ 'present' if longhorn_s3_backup_enabled else 'absent' }}"

    - name: Ensure network policies are deployed
      kubernetes.core.k8s:
        src: networkpolicy.yml
        state: present
