---
- name: Ensure required packages are installed
  become: true
  ansible.builtin.package:
    name:
      - nfs-common
      - open-iscsi
    state: present

- name: Ensure iSCSI initiator name is set and unique
  block:
    - name: Generate new initiator name
      ansible.builtin.command: iscsi-iname
      changed_when: false
      register: iscsi_iname

    - name: Set initiator name
      become: true
      ansible.builtin.copy:
        content: |
          InitiatorName={{ iscsi_iname.stdout }}
        dest: /etc/iscsi/initiatorname.iscsi
        mode: "u=rw,g=,o="
  when: longhorn_generate_iscsi_iname
