---
traefik_ports:
  traefik:
    port: 9000
    protocol: TCP
    expose: false
  web:
    port: 8000
    protocol: TCP
    expose: true
    exposedPort: 80
  websecure:
    port: 8443
    protocol: TCP
    expose: true
    exposedPort: 443
  mysql:
    port: 3306
    protocol: TCP
    expose: true
    exposedPort: 3306
