---
galaxy_info:
  author: dannixon
  description: Installs and configures Longhorn storage driver on a Kubernetes cluster.
  license: MIT

  min_ansible_version: 2.1

  platforms:
    - name: Ubuntu
      versions:
        - focal

dependencies: []
