---
- name: Ensure K3s service file is present
  become: true
  ansible.builtin.template:
    src: k3s_controller.service
    dest: /usr/lib/systemd/system/k3s.service
    owner: root
    group: root
    mode: 0755
  notify: Restart K3s

- name: Ensure K3s node service is enabled and running
  become: true
  ansible.builtin.systemd:
    name: k3s
    daemon_reload: "yes"
    enabled: true
    state: started

- name: Ensure service changes are performed
  ansible.builtin.meta: flush_handlers

- name: Wait for node-token
  become: true
  ansible.builtin.wait_for:
    path: "{{ k3s_server_location }}/server/node-token"

- name: Read node-token from controller
  become: true
  ansible.builtin.slurp:
    path: "{{ k3s_server_location }}/server/node-token"
  register: node_token

- name: Store controller node-token
  ansible.builtin.set_fact:
    token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"

- name: Controller node-token
  ansible.builtin.debug:
    var: token

- name: Retrieve kubeconfig file contents
  become: true
  ansible.builtin.slurp:
    src: /etc/rancher/k3s/k3s.yaml
  register: kubeconfig

- name: Store kubeconfig file contents
  ansible.builtin.set_fact:
    kubeconfig: "{{ kubeconfig.content | b64decode | regex_replace('127\\.0\\.0\\.1', ansible_host) }}"
